name: wallstreetvisionauto
on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:  # Allows manual runs

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas yfinance tqdm discord.py
    - name: Run wallstreetvisionauto
      run: |
        python main_v3.py
        python add_yfinance.py
        python discord_alerts.py
